<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RestaurantTableSeeder extends Seeder
{
    public function run(): void
    {
        $faker = \Faker\Factory::create();
        for ($i = 1; $i <= 10; $i++) {
            $restaurants[] = [
                [
                    'name' => 'Delicious Bites',
                    'email' => 'contact@deliciousbites.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '123 Main Street, City Center',
                    'avatar' => 'restaurant1.jpg',
                    'description' => 'A cozy restaurant serving delightful meals.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Urban Spice',
                    'email' => 'info@urbanspice.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '45 Market Street, Downtown',
                    'avatar' => 'restaurant2.jpg',
                    'description' => 'Experience the best of urban cuisine.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Green Garden Café',
                    'email' => 'hello@greengarden.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '67 Park Avenue, Green District',
                    'avatar' => 'restaurant3.jpg',
                    'description' => 'Fresh and healthy food with a garden view.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Seaside Delights',
                    'email' => 'contact@seasidedelights.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '89 Beach Road, Coastal Area',
                    'avatar' => 'restaurant4.jpg',
                    'description' => 'Enjoy fresh seafood by the sea.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Mountain View Diner',
                    'email' => 'info@mountainview.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '12 Valley Lane, Mountain District',
                    'avatar' => 'restaurant5.jpg',
                    'description' => 'A diner with stunning mountain views.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Classic Flavors',
                    'email' => 'classic@flavors.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '21 Old Town Street, Historic District',
                    'avatar' => 'restaurant6.jpg',
                    'description' => 'Traditional meals made with love.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Modern Eats',
                    'email' => 'hello@moderneats.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '34 Skyline Drive, Downtown',
                    'avatar' => 'restaurant7.jpg',
                    'description' => 'Trendy and modern dishes for every palate.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sunny Side Up',
                    'email' => 'sunny@breakfastparadise.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '56 Sunshine Avenue, Morning Town',
                    'avatar' => 'restaurant8.jpg',
                    'description' => 'Perfect spot for a sunny breakfast.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Night Owl Lounge',
                    'email' => 'nightowl@lounge.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '99 Nightlife Street, City Lights',
                    'avatar' => 'restaurant9.jpg',
                    'description' => 'A place to enjoy food and drinks late at night.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Family Feast',
                    'email' => 'family@feast.com',
                    'phone' => $faker->numerify('+###########'),
                    'address' => '101 Happy Lane, Suburb Area',
                    'avatar' => 'restaurant10.jpg',
                    'description' => 'Perfect for family gatherings with large meals.',
                    'price_start' => rand(50000, 100000),
                    'price_end' => rand(500000, 1000000),
                    'open_time' => '0'.rand(6, 9).':00:00',
                    'close_time' => rand(18, 23).':00:00',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];
        }
    }
}
